[package]
name = "tlser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls-pemfile = "2.0.0"
tokio-rustls = "0.25.0"
